name: learn_flutter_theme
description: Learn flutter heme in this project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  google_fonts: ^2.2.0
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - fonts/google_fonts/

  fonts:
    - family: IRANSans-Medium
      fonts:
        - asset: fonts/IRANSans-Medium.ttf
    - family: IRANSans-Regular
      fonts:
        - asset: fonts/IRANSans-Regular.ttf
    - family: IRANSans-SemiBold
      fonts:
        - asset: fonts/IRANSans-SemiBold.ttf
    - family: IRANSans-Bold
      fonts:
        - asset: fonts/IRANSans-Bold.ttf
